apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aleyna

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app: aleyna
      version: v1

commonAnnotations:
  description: "Aleyna Aygun portfolio website"
